name: ADS-B low altitude alert (San Salvo)

on:
  schedule:
    - cron: "*/5 * * * *"   # ogni 5 minuti (UTC)
  workflow_dispatch:         # avvio manuale

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write        # serve per salvare state.json nel repo
    concurrency:
      group: adsb-monitor-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: python -m pip install --upgrade pip requests

      - name: Restore state
        run: |
          if [ -f state.json ]; then
            echo "State exists"
          else
            echo "{}" > state.json
          fi

      - name: Run monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py

      - name: Persist state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json
          git commit -m "Update state [skip ci]" || echo "No changes"
          git push
